# PROJECT METADATA
name: fitness_tracker_prototype              # APP NAME
description: "A new Flutter project."        # SHORT DESCRIPTION
publish_to: 'none'                           # PRIVATE PROJECT (NOT PUBLISHED TO pub.dev)
version: 1.0.0+1                             # VERSION FORMAT: major.minor.patch+build

# FLUTTER SDK ENVIRONMENT REQUIREMENT
environment:
  sdk: ^3.6.0                                # REQUIRES FLUTTER SDK VERSION 3.6.0 OR HIGHER

# APP DEPENDENCIES
dependencies:

  flutter:
    sdk: flutter                             # CORE FLUTTER SDK

  sqflite: ^2.3.0                            # SQLITE PLUGIN FOR LOCAL DATABASE OPERATIONS
  path: ^1.8.3                               # HELPS CONSTRUCT PATHS FOR FILE SYSTEM

  hive: ^2.2.3                               # LIGHTWEIGHT, NO-SQL DATABASE (USED FOR SESSION STORAGE)
  hive_flutter: ^1.1.0                       # HIVE + FLUTTER INTEGRATION FOR WIDGETS

  provider: 6.1.2                            # STATE MANAGEMENT USING CHANGENOTIFIER

  cupertino_icons: ^1.0.8                    # ICONS THAT MATCH iOS STYLE (USED IN iOS LOOKING COMPONENTS)

  intl: ^0.18.1                              # DATE/TIME FORMATTING UTILITIES (E.G., 'Apr 16, 2025 • 3:45 PM')

  fl_chart: ^0.63.0                          # USED TO DISPLAY PIE CHARTS FOR WORKOUT HISTORY VISUALIZATION

# DEVELOPMENT-ONLY DEPENDENCIES
dev_dependencies:

  flutter_test:
    sdk: flutter                             # TESTING SUPPORT FOR UNIT/WIDGET TESTS

  flutter_lints: ^5.0.0                      # CODE STYLE AND BEST PRACTICE LINTING RULES

# FLUTTER-SPECIFIC CONFIGURATION
flutter:

  uses-material-design: true                 # ENABLES USE OF MATERIAL DESIGN ICONS AND WIDGETS